<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Nama PIC</name>
   <tag></tag>
   <elementGuidId>38052078-92b9-4d33-82b4-3d443c0884b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='id_pic']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;id_pic&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>36c771a2-f266-415d-bea6-19e448e8c4d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d8596ddb-a104-4858-a0c5-e01b2ca5b235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>-Select-</value>
      <webElementGuid>0333b187-6525-4caa-9f89-c88740c537b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>id_pic</value>
      <webElementGuid>c404a494-6f74-4190-a0b0-fbb0ab9168dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-Select-Tris Retno AryaniTris RetnoTris R ATris AryaniTestDev1test uat2Test UAT Project Managet TestProject Manager PrimaMikala FazaLovensia Zukruff AlbasitLala LubanaKaikaikaIben Satriaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiadjasaschDian Aslama NahumaruryDejancsaasAgus Setya</value>
      <webElementGuid>9bbd93b5-0d39-4468-ad4e-6ca4b7c3ce4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;c-app c-default-layout&quot;]/div[@class=&quot;c-wrapper&quot;]/div[@class=&quot;c-body&quot;]/main[@class=&quot;c-main&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;fade show&quot;]/div[@class=&quot;container-mains&quot;]/div[@class=&quot;justify-content-center row&quot;]/div[@class=&quot;col-md-8&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;mb-4 card-body&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;row form-group my-0 mx-2&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;form-group&quot;]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>5356cc51-4169-4fcb-80f5-ec501af62ca8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='id_pic']</value>
      <webElementGuid>89c4ebb2-d243-404b-a9a5-ac890ce49180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/main/div/div/div/div/div/div/div/div[2]/div[2]/div[2]/div/select</value>
      <webElementGuid>2f2d9861-f2c1-4ffc-9e7c-9d7e977f205c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama PIC'])[1]/following::select[1]</value>
      <webElementGuid>a20635ae-731c-4233-9545-fa5c70f3bd91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Cuti'])[1]/following::select[2]</value>
      <webElementGuid>4e4ef513-3169-4671-aa36-b990178b098a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keterangan Cuti'])[1]/preceding::select[1]</value>
      <webElementGuid>a4fa474c-29e9-49f2-b766-337eccb39421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanda Tangan Digital'])[1]/preceding::select[1]</value>
      <webElementGuid>ad4a7cc7-a7e5-4e40-9873-8597e6488b8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>c13c7562-1499-46b9-b6df-1b532c59f485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@placeholder = '-Select-' and @name = 'id_pic' and (text() = '-Select-Tris Retno AryaniTris RetnoTris R ATris AryaniTestDev1test uat2Test UAT Project Managet TestProject Manager PrimaMikala FazaLovensia Zukruff AlbasitLala LubanaKaikaikaIben Satriaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiadjasaschDian Aslama NahumaruryDejancsaasAgus Setya' or . = '-Select-Tris Retno AryaniTris RetnoTris R ATris AryaniTestDev1test uat2Test UAT Project Managet TestProject Manager PrimaMikala FazaLovensia Zukruff AlbasitLala LubanaKaikaikaIben Satriaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiadjasaschDian Aslama NahumaruryDejancsaasAgus Setya')]</value>
      <webElementGuid>b691acf6-a438-4915-a13e-9fd683a85556</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
