<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kegiatan</name>
   <tag></tag>
   <elementGuidId>a61d2f18-4cf3-4236-9f48-ee6b864ad878</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div[3]/div/main/div/div/div/div[4]/div[1]/div/div/form/div/div[2]/div[8]/div[2]/div/select</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
