<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_pengajuanlembur</name>
   <tag></tag>
   <elementGuidId>5c983683-fc3b-4369-9ff6-272ebe6d2157</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>67a5b311-3783-4ae8-b28b-bdb59496aa9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/lembur/pengajuan-lembur</value>
      <webElementGuid>0955425f-402c-4655-bf88-ae0108ebbe73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-dropdown-item-2 d-block overflow-hidden text-truncate</value>
      <webElementGuid>14dade7a-d9ab-4af0-8250-2fbec13c9c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pengajuan Lembur</value>
      <webElementGuid>6c14ed4c-0d53-45d6-bde7-a6832e48d676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;c-app c-default-layout&quot;]/div[@class=&quot;sidebar-dropdown-menu&quot;]/div[1]/div[@class=&quot;custom-dropdown-menu h-100 ml-2 show card&quot;]/li[@class=&quot;custom-sidebar-nav-item&quot;]/a[@class=&quot;custom-dropdown-item-2 d-block overflow-hidden text-truncate&quot;]</value>
      <webElementGuid>0ef76744-0175-42fe-a0b3-b0323d92db6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/li[2]/a</value>
      <webElementGuid>8483a3e4-cb1d-4760-9aba-43f2e3ad058b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pengajuan Lembur')]</value>
      <webElementGuid>b9e5d3ff-4ee9-487c-8710-7c4ee8c0e2a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengajuan Cuti'])[1]/following::a[1]</value>
      <webElementGuid>38fbc36c-1e75-4141-b7d5-1a63bbd717bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cuti dan Lembur'])[1]/following::a[2]</value>
      <webElementGuid>a0d46e22-3c06-41c1-a440-9898dfd8aa6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aplikasi HR SV Jakarta 2023'])[1]/preceding::a[1]</value>
      <webElementGuid>03ce24a3-78e1-484a-bc65-a5a738526c83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View All'])[1]/preceding::a[2]</value>
      <webElementGuid>b1dc41f1-b15b-496b-a2f0-f5ef1a462891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pengajuan Lembur']/parent::*</value>
      <webElementGuid>9f2ac3f2-b176-4aad-ad16-20c0123edc0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#/lembur/pengajuan-lembur')]</value>
      <webElementGuid>f9079110-fcdf-405d-b5cd-a5241f362bb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/li[2]/a</value>
      <webElementGuid>16df39bb-bb46-4464-865a-52080b296e30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/lembur/pengajuan-lembur' and (text() = 'Pengajuan Lembur' or . = 'Pengajuan Lembur')]</value>
      <webElementGuid>29a3e434-eb66-4fc4-8f27-8b959487aafb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
