<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_nama pic</name>
   <tag></tag>
   <elementGuidId>6e07c104-3c15-4279-a509-1a4feded0336</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;id_pic&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='id_pic']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>321fa881-26ac-4c20-8a91-ec5b44ac7fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>45c53904-2026-4aea-9959-e91d38c746b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>-Select-</value>
      <webElementGuid>de9c8aae-254f-4511-9f55-98d13393eaf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>id_pic</value>
      <webElementGuid>3751e504-6bd9-4f31-be42-b776de5a1902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--AdminWafi UlwanWafi UlwanTris Retno AryaniTris RetnoTris R ATris AryaniTommy ShelbyTom SmithTestingDemoAppTestingDemo1TestDev1TestAccountPM1TestAccountKaryawan1test1test1test uat2Test UAT test perpanjangan kontrakTest Karyawan BaruSilvia Amanda rizalRizalRizalrizalrizalrizalrizalRamdanProject Managet TestProject Manager PrimaMuhammad JaenuddinMuhammad JaenuddinMikala FazaMei BarsaLovensia Zukruff AlbasitLala LubanaKaikaikajaya % 123Iben Satriaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaEmployee2employee001djasaschDian Aslama NahumarurydfsdfafDejancsaasasdasdasdasdasdasdAMAYA BRANCHAgus Setyaadasdasd123456789012345678901234567890111</value>
      <webElementGuid>3a75c295-8fae-42a1-9bf0-d349fd37bdfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;c-app c-default-layout&quot;]/div[@class=&quot;c-wrapper&quot;]/div[@class=&quot;c-body&quot;]/main[@class=&quot;c-main&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;fade show&quot;]/div[@class=&quot;container-mains&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;mb-4 card-body&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;row form-group my-0 mx-2&quot;]/div[@class=&quot;col-6&quot;]/div[@class=&quot;form-group&quot;]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>0a433017-be9c-45aa-a81a-99db43bb33e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='id_pic']</value>
      <webElementGuid>3c65de27-bcb0-450e-a079-f87973744701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/main/div/div/div/div/div/div[2]/div[3]/div[2]/div/select</value>
      <webElementGuid>56a4ff8c-0676-4c48-b7ae-3cf947b656a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama PIC'])[1]/following::select[1]</value>
      <webElementGuid>2fa2d2b9-47b3-470e-8def-2c4fc3b5fee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Lembur'])[1]/following::select[2]</value>
      <webElementGuid>915aa51a-1330-4c45-8ea0-cdd5b5c62d57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keterangan Lembur'])[1]/preceding::select[1]</value>
      <webElementGuid>3a392b77-8833-4ff0-a946-70e0b0c290f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanda Tangan Digital'])[1]/preceding::select[1]</value>
      <webElementGuid>05d3ec56-3d1b-460c-98e7-4f3d0df884c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>96e46fa8-7833-4b6a-a2f3-3e4b8ad2a2df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@placeholder = '-Select-' and @name = 'id_pic' and (text() = '--Select--AdminWafi UlwanWafi UlwanTris Retno AryaniTris RetnoTris R ATris AryaniTommy ShelbyTom SmithTestingDemoAppTestingDemo1TestDev1TestAccountPM1TestAccountKaryawan1test1test1test uat2Test UAT test perpanjangan kontrakTest Karyawan BaruSilvia Amanda rizalRizalRizalrizalrizalrizalrizalRamdanProject Managet TestProject Manager PrimaMuhammad JaenuddinMuhammad JaenuddinMikala FazaMei BarsaLovensia Zukruff AlbasitLala LubanaKaikaikajaya % 123Iben Satriaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaEmployee2employee001djasaschDian Aslama NahumarurydfsdfafDejancsaasasdasdasdasdasdasdAMAYA BRANCHAgus Setyaadasdasd123456789012345678901234567890111' or . = '--Select--AdminWafi UlwanWafi UlwanTris Retno AryaniTris RetnoTris R ATris AryaniTommy ShelbyTom SmithTestingDemoAppTestingDemo1TestDev1TestAccountPM1TestAccountKaryawan1test1test1test uat2Test UAT test perpanjangan kontrakTest Karyawan BaruSilvia Amanda rizalRizalRizalrizalrizalrizalrizalRamdanProject Managet TestProject Manager PrimaMuhammad JaenuddinMuhammad JaenuddinMikala FazaMei BarsaLovensia Zukruff AlbasitLala LubanaKaikaikajaya % 123Iben Satriaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaEmployee2employee001djasaschDian Aslama NahumarurydfsdfafDejancsaasasdasdasdasdasdasdAMAYA BRANCHAgus Setyaadasdasd123456789012345678901234567890111')]</value>
      <webElementGuid>5d9f7227-abb0-4bd1-8a81-714f3cee2818</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
